<?php

/**
 * Unit tests for dossier completeness (people-dossier-completeness D1, D3).
 *
 * Rows are shaped like the register's DossierRequirement, PersonnelDocument,
 * HrGeneratedDocument, EmployeeCompetence, EmploymentContract and
 * OrgAssignment, and each is validated against its real schema fragment.
 *
 * @category Test
 * @package  OCA\Humaniq\Tests\Unit\Service
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 * SPDX-License-Identifier: EUPL-1.2
 *
 * @link https://conduction.nl
 *
 * @spec openspec/specs/dossier-completeness/spec.md#REQ-DCP-002
 */

declare(strict_types=1);

namespace OCA\Humaniq\Tests\Unit\Service;

use OCA\Humaniq\Service\AbsenceProgression;
use OCA\Humaniq\Service\DossierCompletenessService;
use OCA\Humaniq\Tests\Unit\Support\RegisterSchemaValidator;
use PHPUnit\Framework\TestCase;

/**
 * Tests for dossier completeness.
 *
 * @spec openspec/specs/dossier-completeness/spec.md#REQ-DCP-002
 */
class DossierCompletenessServiceTest extends TestCase {

	private const DATE = '2026-09-29';

	/**
	 * Every row shape the tests use is a payload the register accepts.
	 *
	 * @return void
	 */
	public function testTheRowsAreValidRegisterPayloads(): void {
		foreach ($this->requirements() as $row) {
			$this->assertSame([], RegisterSchemaValidator::errors('DossierRequirement', $this->strip($row)), $row['code']);
		}

		$this->assertSame([], RegisterSchemaValidator::errors('PersonnelDocument', $this->strip($this->document('id', '2024-01-01', '2031-01-01'))));
	}//end testTheRowsAreValidRegisterPayloads()

	/**
	 * A current ID is present; with no ID at all it is missing.
	 *
	 * @return void
	 */
	public function testPresentAndMissing(): void {
		$rows = $this->rows(documents: [$this->document('id', '2024-01-01', '2031-01-01')]);
		$this->assertSame('aanwezig', $this->statusOf('id', $rows));
		$this->assertSame('PersonnelDocument', $this->rowOf('id', $rows)['evidence']['schema']);

		$this->assertSame('ontbreekt', $this->statusOf('id', $this->rows()));
	}//end testPresentAndMissing()

	/**
	 * An expired ID is verlopen; one inside the warning window is verloopt-binnenkort.
	 *
	 * @return void
	 */
	public function testExpiredAndExpiring(): void {
		$this->assertSame('verlopen', $this->statusOf('id', $this->rows(documents: [$this->document('id', '2016-01-01', '2026-08-31')])));
		$this->assertSame('verloopt-binnenkort', $this->statusOf('id', $this->rows(documents: [$this->document('id', '2016-01-01', '2026-10-29')])));
	}//end testExpiredAndExpiring()

	/**
	 * The newest document wins over an older expired one.
	 *
	 * @return void
	 */
	public function testTheNewestDocumentCounts(): void {
		$rows = $this->rows(documents: [$this->document('id', '2016-01-01', '2026-08-31'), $this->document('id', '2026-08-15', '2036-08-15', 'doc-new')]);

		$this->assertSame('aanwezig', $this->statusOf('id', $rows));
		$this->assertSame('doc-new', $this->rowOf('id', $rows)['evidence']['id']);
	}//end testTheNewestDocumentCounts()

	/**
	 * A VOG issued 200 days before the start date is too old at start.
	 *
	 * @return void
	 */
	public function testAVogIssuedTooLongBeforeTheStartIsTooOld(): void {
		// Start 2025-03-01; 200 days earlier is 2024-08-13.
		$rows = $this->rows(documents: [$this->document('vog', '2024-08-13', null)]);

		$this->assertSame('te-oud-bij-start', $this->statusOf('vog', $rows));

		$rows = $this->rows(documents: [$this->document('vog', '2025-01-15', null)]);
		$this->assertSame('aanwezig', $this->statusOf('vog', $rows));
	}//end testAVogIssuedTooLongBeforeTheStartIsTooOld()

	/**
	 * A BIG registration held as a current competence counts, and names it.
	 *
	 * @return void
	 */
	public function testABigRegistrationHeldAsACompetenceCounts(): void {
		$rows = $this->rows(competences: [['id' => 'comp-1', 'employeeId' => 'emp-1', 'competenceCode' => 'big-verpleegkundige', 'issuedOn' => '2022-01-01', 'validUntil' => '2027-09-29']]);
		$row = $this->rowOf('big', $rows);

		$this->assertSame('aanwezig', $row['status']);
		$this->assertSame(['schema' => 'EmployeeCompetence', 'id' => 'comp-1'], $row['evidence']);
	}//end testABigRegistrationHeldAsACompetenceCounts()

	/**
	 * A signed contract generated by humaniq counts; a failed generation does not.
	 *
	 * @return void
	 */
	public function testAGeneratedContractCounts(): void {
		$generated = ['id' => 'gen-1', 'employeeId' => 'emp-1', 'documentType' => 'arbeidsovereenkomst', 'status' => 'generated', 'generatedAt' => '2025-02-20'];
		$this->assertSame('aanwezig', $this->statusOf('contract', $this->rows(generated: [$generated])));

		$generated['status'] = 'failed';
		$this->assertSame('ontbreekt', $this->statusOf('contract', $this->rows(generated: [$generated])));
	}//end testAGeneratedContractCounts()

	/**
	 * A VOG for the normfunctie Begeleider lists only on a Begeleider's file.
	 *
	 * @return void
	 */
	public function testARequirementAppliesOnlyToItsGroup(): void {
		$service = $this->service();
		$begeleider = $this->rows();
		$codes = array_column($service->statusFor('emp-1', self::DATE, $begeleider), 'requirementCode');
		$this->assertContains('vog', $codes);

		$admin = $this->rows();
		$admin['EmploymentContract'][0]['normfunctieId'] = 'nf-admin';
		$codes = array_column($service->statusFor('emp-1', self::DATE, $admin), 'requirementCode');
		$this->assertNotContains('vog', $codes);
		$this->assertContains('id', $codes);
	}//end testARequirementAppliesOnlyToItsGroup()

	/**
	 * An org-unit requirement follows the current placement; an inactive one never applies.
	 *
	 * @return void
	 */
	public function testOrgUnitScopeAndInactiveRequirements(): void {
		$rows = $this->rows();
		$rows['DossierRequirement'][] = ['code' => 'bhv', 'label' => 'BHV', 'scope' => 'orgUnit', 'scopeValues' => ['unit-1'], 'evidenceKind' => 'personnel-document', 'expires' => true, 'active' => true];
		$rows['DossierRequirement'][] = ['code' => 'old', 'label' => 'Old', 'scope' => 'all', 'evidenceKind' => 'personnel-document', 'active' => false];
		$codes = array_column($this->service()->statusFor('emp-1', self::DATE, $rows), 'requirementCode');
		$this->assertContains('bhv', $codes);
		$this->assertNotContains('old', $codes);

		$rows['OrgAssignment'][0]['endDate'] = '2026-01-01';
		$codes = array_column($this->service()->statusFor('emp-1', self::DATE, $rows), 'requirementCode');
		$this->assertNotContains('bhv', $codes);
	}//end testOrgUnitScopeAndInactiveRequirements()

	/**
	 * A document of another employee is never evidence.
	 *
	 * @return void
	 */
	public function testAnotherEmployeesDocumentIsNotEvidence(): void {
		$doc = $this->document('id', '2024-01-01', '2031-01-01');
		$doc['employeeId'] = 'emp-2';

		$this->assertSame('ontbreekt', $this->statusOf('id', $this->rows(documents: [$doc])));
	}//end testAnotherEmployeesDocumentIsNotEvidence()

	/**
	 * The status of one requirement.
	 *
	 * @param string $code The requirement code.
	 * @param array<string, mixed> $rows The rows.
	 *
	 * @return string
	 */
	private function statusOf(string $code, array $rows): string {
		return (string)$this->rowOf($code, $rows)['status'];
	}//end statusOf()

	/**
	 * The status row of one requirement.
	 *
	 * @param string $code The requirement code.
	 * @param array<string, mixed> $rows The rows.
	 *
	 * @return array<string, mixed>
	 */
	private function rowOf(string $code, array $rows): array {
		foreach ($this->service()->statusFor('emp-1', self::DATE, $rows) as $row) {
			if ($row['requirementCode'] === $code) {
				return $row;
			}
		}

		$this->fail('No status row for ' . $code);
	}//end rowOf()

	/**
	 * The rows for one Begeleider, emp-1, started 2025-03-01, placed in unit-1.
	 *
	 * @param array<int, array<string, mixed>> $documents Personnel documents.
	 * @param array<int, array<string, mixed>> $competences Competences.
	 * @param array<int, array<string, mixed>> $generated Generated documents.
	 *
	 * @return array<string, mixed>
	 */
	private function rows(array $documents = [], array $competences = [], array $generated = []): array {
		return [
			'employee' => ['id' => 'emp-1', 'startDate' => '2025-03-01'],
			'DossierRequirement' => $this->requirements(),
			'EmploymentContract' => [['id' => 'c-1', 'employeeId' => 'emp-1', 'type' => 'permanent', 'normfunctieId' => 'nf-begeleider', 'startDate' => '2025-03-01']],
			'OrgAssignment' => [['id' => 'oa-1', 'employeeId' => 'emp-1', 'orgUnitId' => 'unit-1', 'startDate' => '2025-03-01']],
			'PersonnelDocument' => $documents,
			'HrGeneratedDocument' => $generated,
			'EmployeeCompetence' => $competences,
		];
	}//end rows()

	/**
	 * The four seeded kinds of requirement.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private function requirements(): array {
		return [
			['id' => 'r-id', 'code' => 'id', 'label' => 'Identity document', 'scope' => 'all', 'evidenceKind' => 'personnel-document', 'expires' => true, 'warnDaysBefore' => 60, 'active' => true],
			['id' => 'r-contract', 'code' => 'contract', 'label' => 'Employment contract', 'scope' => 'all', 'evidenceKind' => 'generated-document', 'documentType' => 'arbeidsovereenkomst', 'expires' => false, 'active' => true],
			['id' => 'r-vog', 'code' => 'vog', 'label' => 'Certificate of conduct', 'scope' => 'normfunctie', 'scopeValues' => ['nf-begeleider'], 'evidenceKind' => 'personnel-document', 'expires' => false, 'maxAgeDaysAtStart' => 180, 'active' => true],
			['id' => 'r-big', 'code' => 'big', 'label' => 'BIG registration', 'scope' => 'all', 'evidenceKind' => 'competence', 'competenceCode' => 'big-verpleegkundige', 'expires' => true, 'warnDaysBefore' => 90, 'active' => true],
		];
	}//end requirements()

	/**
	 * One personnel document of emp-1.
	 *
	 * @param string $code The requirement code.
	 * @param string $issuedOn Issue date.
	 * @param string|null $validUntil Expiry date.
	 * @param string $id The id.
	 *
	 * @return array<string, mixed>
	 */
	private function document(string $code, string $issuedOn, ?string $validUntil, string $id = 'doc-1'): array {
		return ['id' => $id, 'employeeId' => 'emp-1', 'requirementCode' => $code, 'issuedOn' => $issuedOn, 'validUntil' => $validUntil];
	}//end document()

	/**
	 * A row without its test id, as a create payload.
	 *
	 * @param array<string, mixed> $row The row.
	 *
	 * @return array<string, mixed>
	 */
	private function strip(array $row): array {
		unset($row['id']);
		$row['employeeId'] = isset($row['employeeId']) ? '5b0c8f0e-2d1b-4c55-9d4e-1a2b3c4d5e6f' : null;
		return array_filter($row, static fn ($v): bool => $v !== null);
	}//end strip()

	/**
	 * The service under test.
	 *
	 * @return DossierCompletenessService
	 */
	private function service(): DossierCompletenessService {
		return new DossierCompletenessService(new AbsenceProgression());
	}//end service()

}//end class
